### ISSUE TITLE
Cannot build because of missing library “jumper”

### ISSUE THREAD

**Issue by jeltsch** [sfultong/stand-in-language#34]
When trying to build SIL using `cabal new-build`, I get the following error message:

    cabal: Missing dependency on a foreign library:
    * Missing (or bad) C library: jumper

Unfortunately, I have no clue what that `jumper` library is and from where to get it.

**Comment by sfultong** [comment]
I've been using nix/cabal for building. I think there's a setting to tell cabal to use nix, but I haven't tried it, so the way I build is:

1. install nix (if you don't have it already)
2. run nix-shell (this will take a while to build all the dependencies)
3. run cabal test/run

**Comment by jeltsch** [comment]
Hmm, I’d like to avoid installing Nix for now. I guess it’s possible to install SIL without Nix. The important point is where to get the `jumper` library from. Interestingly, I cannot find anything about such a library on the web. Does it have some home page? What is it for?

**Comment by jeltsch** [comment]
Aha! Looking at `shell.nix` revealed that `jumper` is actually part of SIL. That helps already.
